baseurl: http://propertycross.com
permalink: /:title
safe: true
lsi: false

debug: false

name: PropertyCross
description: Helping you select a cross-platform mobile framework
url: http://propertycross.com

extensions:
  android: apk
  ios: ipa
  windowsphone: xap
